ciphertext = "ZGHSTNXCAXAEYBQABTEMBNRKLLGWLKULEJRONQUIJMSDPUIIDWZFLIGKCHQNWHKLBHSIZLLMGHPRUFSWOIMHHMLZRZKTFKAXKLDRDPHIELQHPXUNRGWASHXLKRDSTXQNUHWKMZEEYMRETZQAWRBVDWOEZHFFKAMZLLHGAIYLJDVZEOWSDKLWAZRDVAIJMZGHYLUPENWBGQBYSKLYVIPQHKKKHQGHYFUWTBHZSGLENPHOKBEQRBKNEJZSWVUQTLDAIZHEGHJYZYZQHCITBYFZLEXTYCZOITLSDKHHJHYDWOMYTYCWOIVXYCDUXZHEGHUIIDWZFLLAGRHVVPGMPCDTMJMSDZOMZXYDVZSLAPQWOVUTEZVPXCTDCHZMMGPCWVHUAPRWLTVXOADJOZHDTUCIEAPQPFLKTGDQZWGBOBOHVKAZVELEAMTEXSCUNLQHHWKOPQBISJRVMRDWLBYDILEZAPQVTEQXQHQLFOKORDWIGLLMWNMXEMTWCIXRXNGLVGMPKBWVKIZRVLWYBYFWVXNXNZVBERHMRHYZKKTMKLVYBXOOLGUGOHWPSTTYCDAXOKPVLSPHEZNPHWGGLLDGMTZMDDBXEBQBOVXNXOZVHAUFLMRMJGLSHRUAOMSSKLEOWDSKHXGKEBDUVKGODUDLOEPSKLFKTFSBVJZAPLLKROZSSFYYYAHNXSHUYEDQJYZUFSDZSXKJELNYXXTESSEIXOHQZMJXEGHMMKEOVRTETLHQDWTKKFORUESHYNWVRUNDZFYIGZPNIAYXGTOVVRGWFKOKEEAPGDKRKOPQWPPRGZVHZXOFLSHKXNXLQWPWZBNDAJIREPMFLSLM"

#a b c
#d e f
#g h i

#adgcfibeh

#adg
#cfi
#beh

#abc
#def
#ghi

def try_column(column):
	# Split into columns
	columns = [[ciphertext[x] for x in range(i, len(ciphertext), column)] for i in range(0, column)]

	stro = ""
	# Print each character, alternating between columns
	for i in range(0, len(ciphertext) / column):
		alt = False
		for j in range(0, len(columns)):
			if alt:
				stro += columns[j][i]
			else:
				stro += columns[len(columns) - 1 - j][i]

			alt = not alt
	print stro

try_column(4)
try_column(5)
try_column(6)
try_column(7)
try_column(8)