ciphertext = "ZGHSTNXCAXAEYBQABTEMBNRKLLGWLKULEJRONQUIJMSDPUIIDWZFLIGKCHQNWHKLBHSIZLLMGHPRUFSWOIMHHMLZRZKTFKAXKLDRDPHIELQHPXUNRGWASHXLKRDSTXQNUHWKMZEEYMRETZQAWRBVDWOEZHFFKAMZLLHGAIYLJDVZEOWSDKLWAZRDVAIJMZGHYLUPENWBGQBYSKLYVIPQHKKKHQGHYFUWTBHZSGLENPHOKBEQRBKNEJZSWVUQTLDAIZHEGHJYZYZQHCITBYFZLEXTYCZOITLSDKHHJHYDWOMYTYCWOIVXYCDUXZHEGHUIIDWZFLLAGRHVVPGMPCDTMJMSDZOMZXYDVZSLAPQWOVUTEZVPXCTDCHZMMGPCWVHUAPRWLTVXOADJOZHDTUCIEAPQPFLKTGDQZWGBOBOHVKAZVELEAMTEXSCUNLQHHWKOPQBISJRVMRDWLBYDILEZAPQVTEQXQHQLFOKORDWIGLLMWNMXEMTWCIXRXNGLVGMPKBWVKIZRVLWYBYFWVXNXNZVBERHMRHYZKKTMKLVYBXOOLGUGOHWPSTTYCDAXOKPVLSPHEZNPHWGGLLDGMTZMDDBXEBQBOVXNXOZVHAUFLMRMJGLSHRUAOMSSKLEOWDSKHXGKEBDUVKGODUDLOEPSKLFKTFSBVJZAPLLKROZSSFYYYAHNXSHUYEDQJYZUFSDZSXKJELNYXXTESSEIXOHQZMJXEGHMMKEOVRTETLHQDWTKKFORUESHYNWVRUNDZFYIGZPNIAYXGTOVVRGWFKOKEEAPGDKRKOPQWPPRGZVHZXOFLSHKXNXLQWPWZBNDAJIREPMFLSLM"

#abcdefghijklmno

#a b c d e
#f g h i j
#k l m n o

#afkbglchmdinejo
#afk bgl chm din ejo



def try_column(column):
	# Split into blocks
	blk_len = len(ciphertext) / column
	blks = [ciphertext[i:i+blk_len] for i in range(0, len(ciphertext), blk_len)]

	# Re-Arrange Blocks
	start = []
	end = []
	alt = False
	for blk in blks:
		if alt:
			end.insert(0, blk)
		else:
			start.append(blk)
		alt = not alt

	#blks = start + end

	# Print out
	ostr = ""
	for i in range(0, 3):
		for blk in blks:
			if i < len(blk):
				ostr = ostr + blk[i]
	print ostr

try_column(4)
try_column(5)
try_column(6)
try_column(7)
try_column(8)
