from etc import tess26
import random

ciphertext = "RENIRMOLEHFBGONRONEANVSWEUAHHESMGSACLOLITNTWWLFERNIESGNHICGUOUEKLROALONAUIONWENTLUNIOUANHETWWUMELYSLMAHNSSFNTLABTROLETEUHNHPUNRDTOEATNANLMSINRTNSORADYRNCSFWAISABRNTGIEWVEDSHOTENPWCEAELSCOUUOSFIHLOATTWRORIHNNGROSLKRTPTEVINNTWOSCTWNTLRERYHUEERTDIIOELRHHFEDYSAEFBYFRETHPREHTJUHTHOTRGIFONEOGYYEOEAUIOMOSNOEINIRNTANEATHSROOOSHTYGAERBCTRDGTEMTTHNUPISTEFNACILCSFGIREHAPDTTRCTEDOEAHURTOHIUSADSCPAEYNEHOREDLRSEOEESTECHFTTOGIDBEBNGOHAADESIYMDULOATSALSPGHHNMEEXFSEDHPGITEPSLERTMTPTHAVEFOSHHAINBNEGOEEMTYTUAAHSENCOHAFEIHAEELEMEWASRDEHBSNRRMSAOOIUSELSLUGUICTETEHEIUCIEIWIUHENARUDSTHTTDNIUMTCLDERSONOLGLEURNAEYATGDNAFOMFDHEIEDENASLEUSPGHCLTHNCHUCTHEITHIYGDANNOYETKTSOORVLKRPEYYEUAOOTNFRETTYMTPOTTTSJECNTMPOTIGAEOEHFOMETNSATDEEIRYRUIENIEADEBGILBCOIMGETSNORLOLAEETTSHACIMINPOESNTAASTOLWMISOLKRTTRGEWESCBDALXSHYUDENIEDLEECGESAOLURNCTEIUUTORNHHYAPERCSHSRSSMS"

# Split into blocks
blk_len = len(ciphertext) / 6
blks = [ciphertext[i:i+blk_len] for i in range(0, len(ciphertext), blk_len)]


# olololololol brute force.
found = False
while not found:
	random.shuffle(blks)
	ostr = ""
	for i in range(0, blk_len):
		for blk in blks:
			ostr = ostr + blk[i]

	if tess26.tess26.find(ostr) != -1:
		print ostr
		found = True